<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PermissionSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $permissions = [
            // Dashboard
            [
                'id' => 1,
                'module' => 'core',
                'submodule' => 'dashboard',
                'action' => 'view',
                'key' => 'dashboard.view',
                'description' => 'View dashboard',
            ],

            // Employee Management
            [
                'id' => 2,
                'module' => 'hrms',
                'submodule' => 'employees',
                'action' => 'view',
                'key' => 'employees.view',
                'description' => 'View employee list',
            ],
            [
                'id' => 3,
                'module' => 'hrms',
                'submodule' => 'employees',
                'action' => 'create',
                'key' => 'employees.create',
                'description' => 'Create employee',
            ],
            [
                'id' => 4,
                'module' => 'hrms',
                'submodule' => 'employees',
                'action' => 'edit',
                'key' => 'employees.edit',
                'description' => 'Edit employee',
            ],
            [
                'id' => 5,
                'module' => 'hrms',
                'submodule' => 'employees',
                'action' => 'delete',
                'key' => 'employees.delete',
                'description' => 'Delete employee',
            ],
            [
                'id' => 6,
                'module' => 'hrms',
                'submodule' => 'employees',
                'action' => 'performance_view',
                'key' => 'employees.performance.view',
                'description' => 'View employee performance score',
            ],
            [
                'id' => 7,
                'module' => 'hrms',
                'submodule' => 'employee_directory',
                'action' => 'view',
                'key' => 'employees.directory.view',
                'description' => 'View employee directory',
            ],
            [
                'id' => 8,
                'module' => 'hrms',
                'submodule' => 'departments',
                'action' => 'manage',
                'key' => 'departments.manage',
                'description' => 'Manage departments',
            ],
            [
                'id' => 9,
                'module' => 'hrms',
                'submodule' => 'designations',
                'action' => 'manage',
                'key' => 'designations.manage',
                'description' => 'Manage designations',
            ],
            [
                'id' => 10,
                'module' => 'hrms',
                'submodule' => 'organization_hierarchy',
                'action' => 'manage',
                'key' => 'organization_hierarchy.manage',
                'description' => 'Manage organization hierarchy',
            ],
            [
                'id' => 11,
                'module' => 'hrms',
                'submodule' => 'probation',
                'action' => 'manage',
                'key' => 'probation.manage',
                'description' => 'Manage probation and confirmation',
            ],
            [
                'id' => 12,
                'module' => 'hrms',
                'submodule' => 'asset_allocations',
                'action' => 'manage',
                'key' => 'asset_allocations.manage',
                'description' => 'Manage asset allocations',
            ],

            // Self Profile
            [
                'id' => 13,
                'module' => 'hrms',
                'submodule' => 'employee_profile_self',
                'action' => 'view',
                'key' => 'employee_profile_self.view',
                'description' => 'Employee can view own profile',
            ],
            [
                'id' => 14,
                'module' => 'hrms',
                'submodule' => 'employee_profile_self',
                'action' => 'edit_limited',
                'key' => 'employee_profile_self.edit_limited',
                'description' => 'Employee can edit allowed self profile fields',
            ],

            // Attendance
            [
                'id' => 15,
                'module' => 'hrms',
                'submodule' => 'attendance',
                'action' => 'mark',
                'key' => 'attendance.mark',
                'description' => 'Mark attendance',
            ],
            [
                'id' => 16,
                'module' => 'hrms',
                'submodule' => 'attendance',
                'action' => 'view',
                'key' => 'attendance.view',
                'description' => 'View attendance module',
            ],
            [
                'id' => 17,
                'module' => 'hrms',
                'submodule' => 'attendance_records',
                'action' => 'view',
                'key' => 'attendance_records.view',
                'description' => 'View attendance records',
            ],
            [
                'id' => 18,
                'module' => 'hrms',
                'submodule' => 'attendance_rules',
                'action' => 'manage',
                'key' => 'attendance_rules.manage',
                'description' => 'Manage attendance rules',
            ],
            [
                'id' => 19,
                'module' => 'hrms',
                'submodule' => 'attendance_reports',
                'action' => 'generate',
                'key' => 'attendance.report.generate',
                'description' => 'Generate attendance reports',
            ],
            [
                'id' => 20,
                'module' => 'hrms',
                'submodule' => 'attendance_self',
                'action' => 'view',
                'key' => 'attendance_self.view',
                'description' => 'Employee can view own attendance',
            ],
            [
                'id' => 21,
                'module' => 'hrms',
                'submodule' => 'tasks',
                'action' => 'view',
                'key' => 'task.view',
                'description' => 'View task tracking',
            ],

            // Leave
            [
                'id' => 22,
                'module' => 'hrms',
                'submodule' => 'leave',
                'action' => 'allocation_manage',
                'key' => 'leave.allocation.manage',
                'description' => 'Manage leave allocation',
            ],
            [
                'id' => 23,
                'module' => 'hrms',
                'submodule' => 'leave',
                'action' => 'apply',
                'key' => 'leave.apply',
                'description' => 'Apply for leave',
            ],
            [
                'id' => 24,
                'module' => 'hrms',
                'submodule' => 'leave',
                'action' => 'approve',
                'key' => 'leave.approve',
                'description' => 'Approve leave requests',
            ],
            [
                'id' => 25,
                'module' => 'hrms',
                'submodule' => 'leave',
                'action' => 'balance_view',
                'key' => 'leave.balance.view',
                'description' => 'View leave balances',
            ],
            [
                'id' => 26,
                'module' => 'hrms',
                'submodule' => 'holiday',
                'action' => 'manage',
                'key' => 'holiday.manage',
                'description' => 'Manage holiday list',
            ],
            [
                'id' => 27,
                'module' => 'hrms',
                'submodule' => 'leave_self',
                'action' => 'apply',
                'key' => 'leave_self.apply',
                'description' => 'Employee can apply leave',
            ],
            [
                'id' => 28,
                'module' => 'hrms',
                'submodule' => 'leave_self',
                'action' => 'view_balance',
                'key' => 'leave_self.view_balance',
                'description' => 'Employee can view own leave balance',
            ],

            // Payroll
            [
                'id' => 29,
                'module' => 'hrms',
                'submodule' => 'payroll',
                'action' => 'view',
                'key' => 'payroll.view',
                'description' => 'View payroll module',
            ],
            [
                'id' => 30,
                'module' => 'hrms',
                'submodule' => 'payroll',
                'action' => 'structure_manage',
                'key' => 'payroll.structure.manage',
                'description' => 'Manage salary structure',
            ],
            [
                'id' => 31,
                'module' => 'hrms',
                'submodule' => 'payroll',
                'action' => 'dashboard_view',
                'key' => 'payroll.dashboard.view',
                'description' => 'View payroll dashboard',
            ],
            [
                'id' => 32,
                'module' => 'hrms',
                'submodule' => 'payroll',
                'action' => 'payslip_view',
                'key' => 'payroll.payslip.view',
                'description' => 'View payslips',
            ],
            [
                'id' => 33,
                'module' => 'hrms',
                'submodule' => 'payroll',
                'action' => 'fnf_manage',
                'key' => 'payroll.fnf.manage',
                'description' => 'Manage FNF',
            ],
            [
                'id' => 34,
                'module' => 'hrms',
                'submodule' => 'payroll',
                'action' => 'bonus_manage',
                'key' => 'payroll.bonus.manage',
                'description' => 'Manage bonus and incentives',
            ],
            [
                'id' => 35,
                'module' => 'hrms',
                'submodule' => 'payroll_self',
                'action' => 'view_payslip',
                'key' => 'payroll_self.view_payslip',
                'description' => 'Employee can view own payslip',
            ],

            // Documents
            [
                'id' => 36,
                'module' => 'hrms',
                'submodule' => 'documents',
                'action' => 'view',
                'key' => 'documents.view',
                'description' => 'View documents module',
            ],
            [
                'id' => 37,
                'module' => 'hrms',
                'submodule' => 'documents',
                'action' => 'compliance_manage',
                'key' => 'documents.compliance.manage',
                'description' => 'Manage compliance documents',
            ],
            [
                'id' => 38,
                'module' => 'hrms',
                'submodule' => 'documents',
                'action' => 'upload',
                'key' => 'documents.upload',
                'description' => 'Upload documents',
            ],
            [
                'id' => 39,
                'module' => 'hrms',
                'submodule' => 'documents',
                'action' => 'company_view',
                'key' => 'documents.company.view',
                'description' => 'View company documents',
            ],
            [
                'id' => 40,
                'module' => 'hrms',
                'submodule' => 'documents_self',
                'action' => 'upload',
                'key' => 'documents_self.upload',
                'description' => 'Employee can upload own documents',
            ],
            [
                'id' => 41,
                'module' => 'hrms',
                'submodule' => 'documents_self',
                'action' => 'view',
                'key' => 'documents_self.view',
                'description' => 'Employee can view own documents',
            ],

            // Announcements
            [
                'id' => 42,
                'module' => 'hrms',
                'submodule' => 'announcements',
                'action' => 'view',
                'key' => 'announcements.view',
                'description' => 'View announcements',
            ],
            [
                'id' => 43,
                'module' => 'hrms',
                'submodule' => 'announcements',
                'action' => 'create',
                'key' => 'announcements.create',
                'description' => 'Create announcements',
            ],
            [
                'id' => 44,
                'module' => 'hrms',
                'submodule' => 'announcements',
                'action' => 'manage',
                'key' => 'announcements.manage',
                'description' => 'Manage announcements',
            ],
            [
                'id' => 45,
                'module' => 'hrms',
                'submodule' => 'announcements_self',
                'action' => 'view',
                'key' => 'employee.announcements.view',
                'description' => 'Employee can view announcements',
            ],
            [
                'id' => 388,
                'module' => 'hrms',
                'submodule' => 'announcements_self',
                'action' => 'detail',
                'key' => 'employee.announcements.detail',
                'description' => 'Employee can view announcement detail',
            ],

            // Access Control
            [
                'id' => 46,
                'module' => 'access_control',
                'submodule' => 'roles',
                'action' => 'manage',
                'key' => 'roles.manage',
                'description' => 'Manage roles',
            ],
            [
                'id' => 47,
                'module' => 'access_control',
                'submodule' => 'permissions',
                'action' => 'manage',
                'key' => 'permissions.manage',
                'description' => 'Manage permissions',
            ],
            [
                'id' => 48,
                'module' => 'access_control',
                'submodule' => 'admins',
                'action' => 'manage',
                'key' => 'admins.manage',
                'description' => 'Manage admin users',
            ],
            [
                'id' => 49,
                'module' => 'access_control',
                'submodule' => 'module_access',
                'action' => 'manage',
                'key' => 'module_access.manage',
                'description' => 'Manage module access mapping',
            ],

            // Future Modules
            [
                'id' => 50,
                'module' => 'crm',
                'submodule' => 'crm',
                'action' => 'view',
                'key' => 'crm.view',
                'description' => 'View CRM module',
            ],
            [
                'id' => 51,
                'module' => 'project_management',
                'submodule' => 'project_management',
                'action' => 'view',
                'key' => 'project_management.view',
                'description' => 'View Project Management module',
            ],
            [
                'id' => 52,
                'module' => 'finance',
                'submodule' => 'finance',
                'action' => 'view',
                'key' => 'finance.view',
                'description' => 'View Finance module',
            ],
            ['id' => 100, 'module' => 'hrms', 'submodule' => 'leave_dashboard', 'action' => 'view', 'key' => 'hrms.leave.dashboard.view', 'description' => 'View leave dashboard'],
            ['id' => 101, 'module' => 'hrms', 'submodule' => 'leave_request', 'action' => 'view', 'key' => 'hrms.leave.request.view', 'description' => 'View leave requests'],
            ['id' => 102, 'module' => 'hrms', 'submodule' => 'leave_request', 'action' => 'create', 'key' => 'hrms.leave.request.create', 'description' => 'Create leave requests'],
            ['id' => 103, 'module' => 'hrms', 'submodule' => 'leave_request', 'action' => 'cancel', 'key' => 'hrms.leave.request.cancel', 'description' => 'Cancel leave requests'],
            ['id' => 104, 'module' => 'hrms', 'submodule' => 'leave_approval', 'action' => 'view', 'key' => 'hrms.leave.approval.view', 'description' => 'View leave approvals'],
            ['id' => 105, 'module' => 'hrms', 'submodule' => 'leave_approval', 'action' => 'approve', 'key' => 'hrms.leave.approval.approve', 'description' => 'Approve leave requests'],
            ['id' => 106, 'module' => 'hrms', 'submodule' => 'leave_approval', 'action' => 'reject', 'key' => 'hrms.leave.approval.reject', 'description' => 'Reject leave requests'],
            ['id' => 107, 'module' => 'hrms', 'submodule' => 'leave_balance', 'action' => 'view', 'key' => 'hrms.leave.balance.view', 'description' => 'View leave balances'],
            ['id' => 108, 'module' => 'hrms', 'submodule' => 'leave_allocation', 'action' => 'manage', 'key' => 'hrms.leave.allocation.manage', 'description' => 'Manage leave allocations'],
            ['id' => 109, 'module' => 'hrms', 'submodule' => 'leave_type', 'action' => 'manage', 'key' => 'hrms.leave.type.manage', 'description' => 'Manage leave types'],
            ['id' => 110, 'module' => 'hrms', 'submodule' => 'leave_policy', 'action' => 'manage', 'key' => 'hrms.leave.policy.manage', 'description' => 'Manage leave policies'],
            ['id' => 111, 'module' => 'hrms', 'submodule' => 'holiday', 'action' => 'manage', 'key' => 'hrms.holiday.manage', 'description' => 'Manage holidays'],
            ['id' => 112, 'module' => 'hrms', 'submodule' => 'comp_off', 'action' => 'manage', 'key' => 'hrms.comp_off.manage', 'description' => 'Manage comp off'],
        ];

        foreach ($permissions as $permission) {
            DB::table('permissions')->updateOrInsert(
                ['id' => $permission['id']],
                [
                    'module' => $permission['module'],
                    'submodule' => $permission['submodule'],
                    'action' => $permission['action'],
                    'key' => $permission['key'],
                    'description' => $permission['description'],
                    'updated_at' => $now,
                    'created_at' => DB::raw('COALESCE(created_at, NOW())'),
                ]
            );
        }

        $requiredPermissions = [
            [200, 'core', 'dashboard', 'view', 'dashboard.view', 'View dashboard'],
            [201, 'hrms', 'employees', 'view', 'employees.view', 'View employees'],
            [202, 'hrms', 'employees', 'create', 'employees.create', 'Create employees'],
            [203, 'hrms', 'employees', 'edit', 'employees.edit', 'Edit employees'],
            [204, 'hrms', 'employees', 'delete', 'employees.delete', 'Delete employees'],
            [205, 'hrms', 'employees_pending_profiles', 'view', 'employees.pending_profiles.view', 'View pending profiles'],
            [206, 'hrms', 'employees_pending_profiles', 'approve', 'employees.pending_profiles.approve', 'Approve pending profiles'],
            [207, 'hrms', 'employees_probation_internship', 'view', 'employees.probation_internship.view', 'View probation/internship'],
            [208, 'hrms', 'employees_probation_internship', 'manage', 'employees.probation_internship.manage', 'Manage probation/internship'],
            [209, 'hrms', 'employees_exit', 'view', 'employees.exit.view', 'View exits'],
            [210, 'hrms', 'employees_exit', 'manage', 'employees.exit.manage', 'Manage exits'],
            [211, 'hrms', 'employees_organization', 'manage', 'employees.organization.manage', 'Manage organization'],
            [212, 'hrms', 'employees_reporting_structure', 'manage', 'employees.reporting_structure.manage', 'Manage reporting structure'],
            [213, 'hrms', 'attendance_dashboard', 'view', 'attendance.dashboard.view', 'View attendance dashboard'],
            [214, 'hrms', 'attendance_records', 'view', 'attendance.records.view', 'View attendance records'],
            [215, 'hrms', 'attendance_my', 'view', 'attendance.my.view', 'View own attendance'],
            [216, 'hrms', 'attendance_blocked', 'view', 'attendance.blocked.view', 'View blocked attendance'],
            [217, 'hrms', 'attendance_blocked', 'unlock', 'attendance.blocked.unlock', 'Unlock attendance'],
            [218, 'hrms', 'attendance_regularization', 'view', 'attendance.regularization.view', 'View regularization'],
            [219, 'hrms', 'attendance_regularization', 'create', 'attendance.regularization.create', 'Create regularization'],
            [220, 'hrms', 'attendance_regularization', 'approve', 'attendance.regularization.approve', 'Approve regularization'],
            [221, 'hrms', 'attendance_regularization', 'reject', 'attendance.regularization.reject', 'Reject regularization'],
            [222, 'hrms', 'attendance_holiday_work', 'view', 'attendance.holiday_work.view', 'View holiday work'],
            [223, 'hrms', 'attendance_holiday_work', 'approve', 'attendance.holiday_work.approve', 'Approve holiday work'],
            [224, 'hrms', 'attendance_holiday_work', 'reject', 'attendance.holiday_work.reject', 'Reject holiday work'],
            [225, 'hrms', 'attendance_monthly_report', 'view', 'attendance.monthly_report.view', 'View monthly attendance report'],
            [226, 'hrms', 'attendance_monthly_summary', 'view', 'attendance.monthly_summary.view', 'View monthly attendance summary'],
            [227, 'hrms', 'attendance_violations', 'view', 'attendance.violations.view', 'View attendance violations'],
            [228, 'hrms', 'attendance_rules', 'manage', 'attendance.rules.manage', 'Manage attendance rules'],
            [229, 'hrms', 'attendance_types', 'manage', 'attendance.types.manage', 'Manage attendance types'],
            [230, 'hrms', 'attendance_policy_overrides', 'manage', 'attendance.policy_overrides.manage', 'Manage attendance policy overrides'],
            [231, 'hrms', 'attendance_export', 'export', 'attendance.export', 'Export attendance'],
            [232, 'hrms', 'leave_dashboard', 'view', 'leave.dashboard.view', 'View leave dashboard'],
            [233, 'hrms', 'leave_my_requests', 'view', 'leave.my_requests.view', 'View own leave requests'],
            [234, 'hrms', 'leave_my_requests', 'create', 'leave.my_requests.create', 'Create own leave requests'],
            [235, 'hrms', 'leave_my_requests', 'cancel', 'leave.my_requests.cancel', 'Cancel own leave requests'],
            [236, 'hrms', 'leave_approvals', 'view', 'leave.approvals.view', 'View leave approvals'],
            [237, 'hrms', 'leave_approvals', 'approve', 'leave.approvals.approve', 'Approve leave'],
            [238, 'hrms', 'leave_approvals', 'reject', 'leave.approvals.reject', 'Reject leave'],
            [239, 'hrms', 'leave_team_calendar', 'view', 'leave.team_calendar.view', 'View team leave calendar'],
            [240, 'hrms', 'leave_balance', 'view', 'leave.balance.view', 'View leave balance'],
            [241, 'hrms', 'leave_allocation', 'view', 'leave.allocation.view', 'View leave allocation'],
            [242, 'hrms', 'leave_allocation', 'manage', 'leave.allocation.manage', 'Manage leave allocation'],
            [243, 'hrms', 'leave_types', 'manage', 'leave.types.manage', 'Manage leave types'],
            [244, 'hrms', 'leave_policies', 'manage', 'leave.policies.manage', 'Manage leave policies'],
            [245, 'hrms', 'leave_holidays', 'manage', 'leave.holidays.manage', 'Manage leave holidays'],
            [246, 'hrms', 'leave_weekoff_rules', 'manage', 'leave.weekoff_rules.manage', 'Manage weekoff rules'],
            [247, 'hrms', 'leave_comp_off', 'view', 'leave.comp_off.view', 'View comp off'],
            [248, 'hrms', 'leave_comp_off', 'manage', 'leave.comp_off.manage', 'Manage comp off'],
            [249, 'hrms', 'leave_policy_overrides', 'manage', 'leave.policy_overrides.manage', 'Manage leave policy overrides'],
            [250, 'hrms', 'leave_balance_logs', 'view', 'leave.balance_logs.view', 'View leave balance logs'],
            [251, 'hrms', 'payroll_dashboard', 'view', 'payroll.dashboard.view', 'View payroll dashboard'],
            [252, 'hrms', 'payroll_salary_structure', 'view', 'payroll.salary_structure.view', 'View salary structure'],
            [253, 'hrms', 'payroll_salary_structure', 'manage', 'payroll.salary_structure.manage', 'Manage salary structure'],
            [254, 'hrms', 'payroll_attendance_impacts', 'view', 'payroll.attendance_impacts.view', 'View payroll attendance impacts'],
            [255, 'hrms', 'payroll_generate', 'view', 'payroll.generate.view', 'View payroll generation'],
            [256, 'hrms', 'payroll_generate', 'process', 'payroll.generate.process', 'Process payroll'],
            [257, 'hrms', 'payroll_payslips', 'view', 'payroll.payslips.view', 'View payslips'],
            [258, 'hrms', 'payroll_fnf', 'view', 'payroll.fnf.view', 'View FNF'],
            [259, 'hrms', 'payroll_fnf', 'manage', 'payroll.fnf.manage', 'Manage FNF'],
            [260, 'hrms', 'payroll_bonus', 'view', 'payroll.bonus.view', 'View bonus'],
            [261, 'hrms', 'payroll_bonus', 'manage', 'payroll.bonus.manage', 'Manage bonus'],
            [262, 'hrms', 'payroll_monthly_summary', 'view', 'payroll.monthly_summary.view', 'View monthly payroll summary'],
            [263, 'hrms', 'documents_compliance', 'view', 'documents.compliance.view', 'View document compliance'],
            [264, 'hrms', 'documents_upload', 'self', 'documents.upload.self', 'Upload own documents'],
            [265, 'hrms', 'documents_company', 'view', 'documents.company.view', 'View company documents'],
            [266, 'hrms', 'documents_types', 'manage', 'documents.types.manage', 'Manage document types'],
            [267, 'hrms', 'documents_verification', 'view', 'documents.verification.view', 'View document verification'],
            [268, 'hrms', 'documents_verification', 'approve', 'documents.verification.approve', 'Approve document verification'],
            [269, 'hrms', 'documents_verification', 'reject', 'documents.verification.reject', 'Reject document verification'],
            [270, 'hrms', 'announcements', 'view', 'announcements.view', 'View announcements'],
            [271, 'hrms', 'announcements', 'create', 'announcements.create', 'Create announcements'],
            [272, 'hrms', 'announcements', 'edit', 'announcements.edit', 'Edit announcements'],
            [273, 'hrms', 'announcements', 'delete', 'announcements.delete', 'Delete announcements'],
            [274, 'hrms', 'announcements', 'publish', 'announcements.publish', 'Publish announcements'],
            [389, 'hrms', 'announcements', 'print', 'announcements.print', 'Print announcements'],
            [275, 'access_control', 'roles', 'manage', 'access.roles.manage', 'Manage roles'],
            [276, 'access_control', 'permissions', 'manage', 'access.permissions.manage', 'Manage permissions'],
            [277, 'access_control', 'admins', 'manage', 'access.admins.manage', 'Manage admins'],
            [278, 'settings', 'system', 'manage', 'settings.system.manage', 'Manage system settings'],
            [279, 'settings', 'company', 'manage', 'settings.company.manage', 'Manage company settings'],
            [280, 'settings', 'profile', 'view', 'settings.profile.view', 'View profile'],
            [281, 'settings', 'profile', 'update', 'settings.profile.update', 'Update profile'],
            [282, 'settings', 'policy_change_logs', 'view', 'settings.policy_change_logs.view', 'View policy change logs'],
            [283, 'settings', 'employee_policy_assignments', 'view', 'settings.employee_policy_assignments.view', 'View employee policy assignments'],
            [284, 'settings', 'employee_policy_assignments', 'manage', 'settings.employee_policy_assignments.manage', 'Manage employee policy assignments'],
            [285, 'settings', 'notification_retention', 'manage', 'settings.notification_retention.manage', 'Manage notification retention'],
            [286, 'crm', 'crm', 'view', 'crm.view', 'View CRM'],
            [287, 'hrms', 'documents_legacy', 'view', 'employee_documents.view', 'Legacy employee document view'],
            [288, 'hrms', 'documents_legacy', 'manage', 'company_documents.manage', 'Legacy company document manage'],
            [289, 'hrms', 'documents_self_legacy', 'view', 'documents_self.view', 'Legacy self document view'],
            [290, 'hrms', 'documents_self_legacy', 'upload', 'documents_self.upload', 'Legacy self document upload'],
            [291, 'hrms', 'employees_legacy', 'view', 'employee.view', 'Legacy employee view'],
            [292, 'hrms', 'attendance_weekoff_rules', 'manage', 'attendance.weekoff_rules.manage', 'Manage attendance weekoff rules'],
            [293, 'hrms', 'attendance_holidays', 'manage', 'attendance.holidays.manage', 'Manage attendance holidays'],
        ];

        foreach ($requiredPermissions as [$id, $module, $submodule, $action, $key, $description]) {
            $existingId = DB::table('permissions')->where('key', $key)->value('id');

            if ($existingId) {
                DB::table('permissions')->where('key', $key)->update([
                    'module' => $module,
                    'submodule' => $submodule,
                    'action' => $action,
                    'description' => $description,
                    'updated_at' => $now,
                ]);
                continue;
            }

            DB::table('permissions')->updateOrInsert(
                ['id' => $id],
                [
                    'id' => $id,
                    'key' => $key,
                    'module' => $module,
                    'submodule' => $submodule,
                    'action' => $action,
                    'created_at' => DB::raw('COALESCE(created_at, NOW())'),
                    'description' => $description,
                    'updated_at' => $now,
                ]
            );
        }

        $runtimePermissions = [
            ['hrms', 'attendance_records', 'view_all', 'attendance.records.view_all', 'View all attendance records'],
            ['hrms', 'attendance_regularization', 'view_own', 'attendance.regularization.view_own', 'View own regularization requests'],
            ['hrms', 'attendance_regularization', 'view_team', 'attendance.regularization.view_team', 'View team regularization requests'],
            ['hrms', 'attendance_regularization', 'view_all', 'attendance.regularization.view_all', 'View all regularization requests'],
            ['hrms', 'attendance_holiday_work', 'manage', 'attendance.holiday_work.manage', 'Manage holiday work requests'],
            ['hrms', 'attendance_monthly_report', 'view_own', 'attendance.monthly_report.view_own', 'View own monthly attendance report'],
            ['hrms', 'attendance_monthly_report', 'view_team', 'attendance.monthly_report.view_team', 'View team monthly attendance report'],
            ['hrms', 'attendance_monthly_report', 'view_all', 'attendance.monthly_report.view_all', 'View all monthly attendance reports'],
            ['hrms', 'leave_approvals', 'view_team', 'leave.approvals.view_team', 'View team leave approvals'],
            ['hrms', 'leave_approvals', 'view_all', 'leave.approvals.view_all', 'View all leave approvals'],
            ['hrms', 'leave_balance', 'view_own', 'leave.balance.view_own', 'View own leave balance'],
            ['hrms', 'leave_balance', 'view_team', 'leave.balance.view_team', 'View team leave balances'],
            ['hrms', 'leave_balance', 'view_all', 'leave.balance.view_all', 'View all leave balances'],
            ['hrms', 'leave_allocation', 'view_own', 'leave.allocation.view_own', 'View own leave allocation'],
            ['hrms', 'leave_allocation', 'view_all', 'leave.allocation.view_all', 'View all leave allocations'],
            ['hrms', 'leave_comp_off', 'view_own', 'leave.comp_off.view_own', 'View own comp off'],
            ['hrms', 'leave_comp_off', 'view_all', 'leave.comp_off.view_all', 'View all comp off'],
            ['hrms', 'payroll_payslips', 'view_own', 'payroll.payslips.view_own', 'View own payslips'],
            ['hrms', 'payroll_payslips', 'view_all', 'payroll.payslips.view_all', 'View all payslips'],
            ['hrms', 'payroll', 'approve', 'payroll.approve', 'Approve generated payroll'],
            ['hrms', 'payroll_claims', 'view_all', 'payroll.claims.view_all', 'View all reimbursement claims'],
            ['hrms', 'payroll_claims', 'manage', 'payroll.claims.manage', 'Approve or reject reimbursement claims'],
            ['hrms', 'payroll_adjustments', 'manage', 'payroll.adjustments.manage', 'Manage payroll bonus, incentive, TDS and deductions'],
            ['settings', 'mobile_app_versions', 'view', 'mobile_app_versions.view', 'View mobile app versions'],
            ['settings', 'mobile_app_versions', 'manage', 'mobile_app_versions.manage', 'Manage mobile app versions'],
            ['settings', 'mobile_app_versions', 'upload', 'mobile_app_versions.upload', 'Upload mobile APK releases'],
            ['settings', 'mobile_app_versions', 'delete', 'mobile_app_versions.delete', 'Delete mobile APK releases'],
            ['hrms', 'enterprise_payroll_self', 'view_payslips', 'enterprise_payroll.my_payslips.view', 'Employee can view own payslips'],
            ['hrms', 'enterprise_payroll_self', 'view_reimbursements', 'enterprise_payroll.my_reimbursements.view', 'Employee can view own reimbursements'],
            ['hrms', 'enterprise_payroll_self', 'create_reimbursements', 'enterprise_payroll.my_reimbursements.create', 'Employee can apply for reimbursement'],
            ['hrms', 'enterprise_payroll', 'dashboard_view', 'enterprise_payroll.dashboard.view', 'View enterprise payroll dashboard'],
            ['hrms', 'enterprise_payroll', 'salary_structure_view', 'enterprise_salary_structure.view', 'View enterprise salary structure'],
            ['hrms', 'enterprise_payroll', 'salary_structure_manage', 'enterprise_salary_structure.manage', 'Manage enterprise salary structure'],
            ['hrms', 'enterprise_payroll', 'payroll_run_view', 'enterprise_payroll_run.view', 'View enterprise payroll run'],
            ['hrms', 'enterprise_payroll', 'payroll_run_generate', 'enterprise_payroll_run.generate', 'Generate enterprise payroll run'],
            ['hrms', 'enterprise_payroll', 'payroll_run_approve', 'enterprise_payroll_run.approve', 'Approve enterprise payroll run'],
            ['hrms', 'enterprise_payroll', 'payroll_run_lock', 'enterprise_payroll_run.lock', 'Lock enterprise payroll run'],
            ['hrms', 'enterprise_payroll', 'payroll_run_reopen', 'enterprise_payroll_run.reopen', 'Reopen enterprise payroll run'],
            ['hrms', 'enterprise_payroll', 'payslip_view', 'enterprise_payslip.view', 'View enterprise payslips'],
            ['hrms', 'enterprise_payroll', 'payslip_generate', 'enterprise_payslip.generate', 'Generate enterprise payslips'],
            ['hrms', 'enterprise_payroll', 'payslip_download', 'enterprise_payslip.download', 'Download enterprise payslips'],
            ['hrms', 'enterprise_payroll', 'bonus_incentive_view', 'enterprise_bonus_incentive.view', 'View enterprise bonus and incentives'],
            ['hrms', 'enterprise_payroll', 'bonus_incentive_manage', 'enterprise_bonus_incentive.manage', 'Manage enterprise bonus and incentives'],
            ['hrms', 'enterprise_payroll', 'reimbursement_view', 'enterprise_reimbursement.view', 'View enterprise reimbursements'],
            ['hrms', 'enterprise_payroll', 'reimbursement_manage', 'enterprise_reimbursement.manage', 'Manage enterprise reimbursements'],
            ['hrms', 'enterprise_payroll', 'fnf_view', 'enterprise_fnf.view', 'View enterprise FNF settlements'],
            ['hrms', 'enterprise_payroll', 'fnf_manage', 'enterprise_fnf.manage', 'Manage enterprise FNF settlements'],
            ['hrms', 'enterprise_payroll', 'reports_view', 'enterprise_payroll_reports.view', 'View enterprise payroll reports'],
        ];

        foreach ($runtimePermissions as [$module, $submodule, $action, $key, $description]) {
            DB::table('permissions')->updateOrInsert(
                ['key' => $key],
                [
                    'module' => $module,
                    'submodule' => $submodule,
                    'action' => $action,
                    'description' => $description,
                    'updated_at' => $now,
                    'created_at' => DB::raw('COALESCE(created_at, NOW())'),
                ]
            );
        }
    }
}
