{{-- Tree View Toolbar (Zoom, Counters, Expand/Collapse) --}}
<div id="treeToolbar" class="eo-tree-toolbar">
    <div class="eo-toolbar-left">
        <span id="matchCounterBadge" class="eo-counter-badge">
            <i class="fas fa-users"></i> Loading employees...
        </span>
    </div>
    <div class="eo-toolbar-right">
        <button type="button" id="btnZoomOut" class="eo-tool-btn" title="Zoom Out">
            <i class="fas fa-search-minus"></i>
        </button>
        <span id="zoomLevelText" class="eo-zoom-text">100%</span>
        <button type="button" id="btnZoomIn" class="eo-tool-btn" title="Zoom In">
            <i class="fas fa-search-plus"></i>
        </button>
        <button type="button" id="btnResetZoom" class="eo-tool-btn" title="Reset Zoom">
            <i class="fas fa-compress-arrows-alt"></i> Fit
        </button>
        <span class="eo-tool-divider"></span>
        <button type="button" id="btnExpandAll" class="eo-tool-btn" title="Expand All Branches">
            <i class="fas fa-expand-alt"></i> Expand All
        </button>
        <button type="button" id="btnCollapseAll" class="eo-tool-btn" title="Collapse All Branches">
            <i class="fas fa-compress-alt"></i> Collapse All
        </button>
    </div>
</div>

{{-- Tree Visualization Viewport --}}
<div id="treeViewContainer" class="eo-tree-container">
    <div id="orgTreeWrapper" class="org-tree">
        {{-- Tree dynamically generated by JavaScript --}}
    </div>
</div>

{{-- Stacked List Viewport --}}
<div id="listViewContainer" class="eo-list-container" style="display:none;">
    <div id="stackedListWrapper">
        {{-- Stacked list dynamically generated by JavaScript --}}
    </div>
</div>

{{-- Empty State Container --}}
<div id="emptyStateContainer" class="eo-empty-state" style="display:none;">
    <div class="eo-empty-icon">
        <i class="fas fa-users-slash"></i>
    </div>
    <h5 class="eo-empty-title">No reporting structure available.</h5>
    <p class="eo-empty-sub">No active employees matching the selected filters were found in the organization chart.</p>
</div>
