<?php
require __DIR__ . '/Web/hrms/employee.php';
require __DIR__ . '/Web/hrms/organization.php';
require __DIR__ . '/Web/hrms/asset.php';
require __DIR__ . '/Web/hrms/document.php';
require __DIR__ . '/Web/hrms/notification.php';
require __DIR__ . '/Web/hrms/announcements.php';
require __DIR__ . '/Web/hrms/recruitment.php';
require __DIR__ . '/Web/hrms/attendance.php';
require __DIR__ . '/Web/hrms/leave.php';
require __DIR__ . '/Web/hrms/enterprise_payroll.php';
require __DIR__ . '/Web/hrms/mobile_app.php';
require __DIR__ . '/Web/auth.php';
require __DIR__ . '/Web/dashboard.php';
require __DIR__ . '/Web/settings.php';
require __DIR__ . '/Web/crm/crm.php';
require __DIR__ . '/Web/access_control.php';
require __DIR__ . '/Web/project_management/project_management.php';
require __DIR__ . '/Web/project_management/task.php';
